version: "3.8"

services:
  db:
    image: mongo:7
    container_name: pricing-app
    environment:
      MONGO_INITDB_ROOT_USERNAME: pricing
      MONGO_INITDB_ROOT_PASSWORD: Godwin26052
      MONGO_INITDB_DATABASE: pricing-api
    ports:
      - "5433:27017"
    volumes:
      - db_data:/data/db

volumes:
  db_data:
    driver: local